### ISSUE TITLE
possible sensitive data exposure in early commits 

### ISSUE THREAD

**Issue by evba1** [flexie-crm/fiskalizimi-sdk-php#2]
I check some of the first commits and noticed that some possible personal data have been included in the code.

**Comment by flexie-crm** [comment]
Hi there Evi, thanks for creating this issue, appreciate it! 

Those data are just for demo purpose, and all endpoints and API keys are just for testing environment, so developers coming across this, have a better experience on getting this package and running/trying it right away, without worrying on where to get keys or sample data.

Best Regards,
Eriol G.

**Comment by evba1** [comment]
@flexie-crm I was referring more to some personal id and bank details informations because they looked too realistic to be just for demo purpose like in [here](https://github.com/flexie-crm/fiskalizimi-sdk-php/commit/8c2b70b209c8d94849b13b4b50ea158827260265) Anyway if that is the case we close this out.
